backend:
  name: github
  repo: Wolf-Quiteque/jmc
  branch: main

media_folder: "img" 

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - {name: "title", label: "Title", widget: "string"}
      - {name: "subtitle", label: "Subtitle", widget: "string"}
      - {name: "banner_image", label: "Banner Image", widget: "image"}
      - name: "general_info"
        label: "General Information"
        widget: "object"
        fields:
          - {name: "paragraph", label: "Paragraph", widget: "text"}
          - name: "features"
            label: "Features"
            widget: "list"
            fields:
              - {name: "text", label: "Text", widget: "string"}
      - {name: "catalog_pdf", label: "Catalog PDF", widget: "file"}
      - name: "specifications"
        label: "Specifications"
        widget: "list"
        fields:
          - {name: "icon", label: "Icon Class", widget: "string"}
          - {name: "label", label: "Label", widget: "string"}
          - {name: "value", label: "Value", widget: "string"}
      - name: "exterior_design"
        label: "Exterior Design"
        widget: "list"
        fields:
          - {name: "image", label: "Image", widget: "image"}
          - {name: "title", label: "Title", widget: "string"}
      - name: "interior_design"
        label: "Interior Design"
        widget: "list"
        fields:
          - {name: "image", label: "Image", widget: "image"}
          - {name: "title", label: "Title", widget: "string"}
